/*
 * Copyright 2026 Navix Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.navix.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

/**
 * Generates a typed navigation extension file per module.
 *
 * For each [@RouteDestination][io.navix.annotations.RouteDestination] class, a `Navigator`
 * extension function is emitted that constructs the route and calls [Navigator.push]:
 *
 * ```kotlin
 * // Generated — do not edit
 * // For: data object Home : Route
 * fun Navigator.navigateToHome(transition: NavTransitionKey = NavTransitionKey.Default) {
 *     push(Home, transition)
 * }
 *
 * // For: data class ProductDetail(val productId: String) : Route
 * fun Navigator.navigateToProductDetail(
 *     productId: String,
 *     transition: NavTransitionKey = NavTransitionKey.Default,
 * ) {
 *     push(ProductDetail(productId = productId), transition)
 * }
 * ```
 *
 * ### Why generated extensions?
 * Callers no longer need to know the route's constructor signature. Renaming a route
 * parameter is a single KSP re-run away from propagating everywhere. The extension is
 * the stable call-site; the route class is the internal representation.
 */
internal class NavixExtensionsGenerator(
    private val codeGenerator: CodeGenerator
) {
    fun generate(descriptors: List<RouteDestinationDescriptor>, moduleName: String) {
        if (descriptors.isEmpty()) return

        val sanitized =
            moduleName
                .replaceFirstChar { it.uppercaseChar() }
                .replace(Regex("[^a-zA-Z0-9]"), "")
        val fileName = "${sanitized}NavixExtensions"
        val packageName = "io.navix.generated"

        val source =
            buildString {
                appendLine("// Generated by Navix Compiler — do not edit")
                appendLine("package $packageName")
                appendLine()
                appendLine("import io.navix.contracts.NavTransitionKey")
                appendLine("import io.navix.runtime.Navigator")
                // Collect all unique import packages for route classes
                descriptors
                    .sortedBy { it.fullyQualifiedName }
                    .map { it.packageName }
                    .distinct()
                    .forEach { pkg -> appendLine("import $pkg.*") }
                appendLine()

                descriptors.sortedBy { it.fullyQualifiedName }.forEach { descriptor ->
                    append(generateExtension(descriptor))
                    appendLine()
                }
            }

        codeGenerator
            .createNewFile(
                dependencies = Dependencies(aggregating = true),
                packageName = packageName,
                fileName = fileName
            ).use { stream ->
                stream.write(source.toByteArray())
            }
    }

    private fun generateExtension(descriptor: RouteDestinationDescriptor): String {
        return buildString {
            val fnName = "navigateTo${descriptor.className}"
            val params = descriptor.constructorParams

            appendLine("/** Navigates to [${descriptor.className}]. Generated by Navix KSP compiler. */")
            if (params.isEmpty()) {
                // data object route — no constructor args
                appendLine("fun Navigator.$fnName(")
                appendLine("    transition: NavTransitionKey = NavTransitionKey.Default,")
                appendLine(") {")
                appendLine("    push(${descriptor.className}, transition)")
                appendLine("}")
            } else {
                // data class route — mirror constructor params
                appendLine("fun Navigator.$fnName(")
                params.forEach { param ->
                    appendLine("    ${param.name}: ${param.typeName},")
                }
                appendLine("    transition: NavTransitionKey = NavTransitionKey.Default,")
                appendLine(") {")
                val argList = params.joinToString(", ") { "${it.name} = ${it.name}" }
                appendLine("    push(${descriptor.className}($argList), transition)")
                appendLine("}")
            }
        }
    }
}
