/*
 * Copyright 2026 Navix Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.navix.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

/**
 * Generates a `NavixRouteRegistry` implementation that lists all discovered destinations.
 *
 * Output example for a module named "checkout" containing [CheckoutRoute]:
 * ```kotlin
 * // Generated — do not edit
 * package io.navix.generated
 *
 * object CheckoutNavixRouteRegistry : NavixRouteRegistry {
 *     override val destinations: List<String> = listOf(
 *         "io.checkout.CheckoutRoute",
 *     )
 * }
 * ```
 *
 * The registry is consumed by [NavixHost] when composing multi-module graphs.
 */
internal class RouteRegistryGenerator(
    private val codeGenerator: CodeGenerator,
) {
    fun generate(
        descriptors: List<RouteDestinationDescriptor>,
        moduleName: String,
    ) {
        if (descriptors.isEmpty()) return

        val sanitized =
            moduleName
                .replaceFirstChar { it.uppercaseChar() }
                .replace(Regex("[^a-zA-Z0-9]"), "")
        val objectName = "${sanitized}NavixRouteRegistry"
        val packageName = "io.navix.generated"

        val destinations =
            descriptors
                .sortedBy { it.fullyQualifiedName }
                .joinToString(",\n        ") { "\"${it.fullyQualifiedName}\"" }

        val source =
            buildString {
                appendLine("// Generated by Navix Compiler — do not edit")
                appendLine("package $packageName")
                appendLine()
                appendLine("import io.navix.runtime.NavixRouteRegistry")
                appendLine()
                appendLine("object $objectName : NavixRouteRegistry {")
                appendLine("    override val destinations: List<String> = listOf(")
                appendLine("        $destinations")
                appendLine("    )")
                appendLine("}")
            }

        codeGenerator
            .createNewFile(
                dependencies = Dependencies(aggregating = true),
                packageName = packageName,
                fileName = objectName,
            ).use { stream ->
                stream.write(source.toByteArray())
            }
    }
}
