/*
 * Copyright 2026 Navix Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.navix.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

/**
 * Generates a `SerializersModule` that registers every `@RouteDestination`-annotated class as a
 * polymorphic subclass of `Route`.
 *
 * The generated module is consumed by [io.navix.runtime.JsonNavigatorSaver] to enable
 * JSON serialization of [io.navix.contracts.BackstackSnapshot] — the structure that the runtime
 * persists across process death via [io.navix.compose.rememberSaveableNavigator].
 *
 * ### Generated output (module = "checkout", routes = [CheckoutRoute, CartRoute])
 * ```kotlin
 * // Generated by Navix Compiler — do not edit
 * package io.navix.generated
 *
 * import io.navix.contracts.Route
 * import kotlinx.serialization.modules.SerializersModule
 * import kotlinx.serialization.modules.polymorphic
 * import kotlinx.serialization.modules.subclass
 *
 * val CheckoutNavixSerializersModule: SerializersModule = SerializersModule {
 *     polymorphic(Route::class) {
 *         subclass(io.checkout.CheckoutRoute::class)
 *         subclass(io.checkout.CartRoute::class)
 *     }
 * }
 * ```
 *
 * ### Multi-module usage
 * Each module produces its own `${Module}NavixSerializersModule`. At the app entrypoint
 * combine them with `+`:
 * ```kotlin
 * val saver = JsonNavigatorSaver(
 *     routesModule = CheckoutNavixSerializersModule + AppNavixSerializersModule
 * )
 * ```
 */
internal class SerializersModuleGenerator(
    private val codeGenerator: CodeGenerator,
) {
    fun generate(
        descriptors: List<RouteDestinationDescriptor>,
        moduleName: String,
    ) {
        if (descriptors.isEmpty()) return

        val (valName, source) = buildSerializersModuleSource(descriptors, moduleName)
        val packageName = "io.navix.generated"

        codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true),
            packageName = packageName,
            fileName = valName,
        ).use { stream ->
            stream.write(source.toByteArray())
        }
    }
}

/**
 * Pure string-building logic, separated for unit testing without a [CodeGenerator].
 *
 * @return Pair of (fileName, sourceCode) — the file name matches the generated `val` name.
 */
internal fun buildSerializersModuleSource(
    descriptors: List<RouteDestinationDescriptor>,
    moduleName: String,
): Pair<String, String> {
    val sanitized =
        moduleName.replaceFirstChar { it.uppercaseChar() }
            .replace(Regex("[^a-zA-Z0-9]"), "")
    val valName = "${sanitized}NavixSerializersModule"
    val packageName = "io.navix.generated"

    val subclasses =
        descriptors
            .sortedBy { it.fullyQualifiedName }
            .joinToString("\n        ") { "subclass(${it.fullyQualifiedName}::class)" }

    val source =
        buildString {
            appendLine("// Generated by Navix Compiler — do not edit")
            appendLine("package $packageName")
            appendLine()
            appendLine("import io.navix.contracts.Route")
            appendLine("import kotlinx.serialization.modules.SerializersModule")
            appendLine("import kotlinx.serialization.modules.polymorphic")
            appendLine("import kotlinx.serialization.modules.subclass")
            appendLine()
            appendLine("val $valName: SerializersModule = SerializersModule {")
            appendLine("    polymorphic(Route::class) {")
            appendLine("        $subclasses")
            appendLine("    }")
            appendLine("}")
        }
    return valName to source
}
