/*
 * Copyright 2026 Navix Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.navix.runtime

/**
 * Provides a list of fully-qualified [io.navix.contracts.Route] class names
 * for a single module's navigation graph.
 *
 * Implementations are generated by the KSP compiler for each module that
 * declares [@io.navix.annotations.RouteDestination] classes. Multiple registries
 * are composed at the [NavixHost] call site to build multi-module graphs.
 *
 * Manual implementations are fully supported — KSP is optional.
 */
interface NavixRouteRegistry {
    val destinations: List<String>
}
