/*
 * Copyright 2026 Navix Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.navix.compiler

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Unit tests for [buildDeepLinkHandlerSource] — the pure source-building core
 * extracted from [DeepLinkHandlerGenerator].
 *
 * Tests verify the generated handler uses `?: return null` (graceful fallback) instead
 * of `?: error(...)` (crashing the handleDeepLink call site) when a URI capture group
 * is unexpectedly absent. No KSP [com.google.devtools.ksp.processing.CodeGenerator]
 * is involved; tests run as plain JVM unit tests.
 */
class DeepLinkHandlerGeneratorTest {

    @Test
    fun buildSource_noDeepLinkTemplates_returnsNull() {
        val descriptor = descriptor("com.example.HomeRoute", templates = emptyList())
        assertNull(buildDeepLinkHandlerSource(descriptor))
    }

    @Test
    fun buildSource_withTemplate_containsPackageDeclaration() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("package io.navix.generated"))
    }

    @Test
    fun buildSource_withTemplate_containsDoNotEditComment() {
        val source = buildSourceForProduct()
        assertTrue(source.trimStart().startsWith("// Generated by Navix Compiler"))
    }

    @Test
    fun buildSource_withTemplate_importsDeepLinkHandler() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("import io.navix.runtime.DeepLinkHandler"))
    }

    @Test
    fun buildSource_withTemplate_importsRoute() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("import io.navix.contracts.Route"))
    }

    @Test
    fun buildSource_withTemplate_generatesCorrectClassName() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("class ProductDetailDeepLinkHandler : DeepLinkHandler"))
    }

    @Test
    fun buildSource_withSingleParam_usesReturnNullNotError() {
        val source = buildSourceForProduct()
        // Must NOT use throwing error()
        assertFalse(
            source.contains("error("),
            "Generated handler must NOT use error() — it must return null gracefully."
        )
        // Must use non-local return null for graceful fallback
        assertTrue(
            source.contains("?: return null"),
            "Generated handler must use '?: return null' to fall through gracefully."
        )
    }

    @Test
    fun buildSource_withMultipleParams_allParamsUseReturnNull() {
        val template = DeepLinkTemplateParser.parse("myapp://shop/{category}/{itemId}").getOrThrow()
        val descriptor = descriptor(
            fqn = "com.example.ShopRoute",
            templates = listOf(template)
        )
        val source = buildDeepLinkHandlerSource(descriptor)
        assertNotNull(source)
        assertFalse(source.contains("error("), "No param should use error() — all must return null.")
        // Both params must have the fallback
        val returnNullCount = source.split("?: return null").size - 1
        assertTrue(
            returnNullCount >= 2,
            "Expected at least 2 '?: return null' occurrences (one per param), got $returnNullCount."
        )
    }

    @Test
    fun buildSource_withNoParams_doesNotContainReturnNullFallback() {
        // A route with no path params needs no fallback — confirm no false positives.
        val template = DeepLinkTemplateParser.parse("myapp://home").getOrThrow()
        val descriptor = descriptor("com.example.HomeRoute", templates = listOf(template))
        val source = buildDeepLinkHandlerSource(descriptor)
        assertNotNull(source)
        assertFalse(source.contains("error("))
        // No param coercion means no `?: return null` inside the let block
        // (the outer `return null` at the end of resolve() is still present though)
        assertTrue(source.contains("return null"))
    }

    @Test
    fun buildSource_withSingleParam_usesPositionalGroupNotNamedGroupString() {
        val source = buildSourceForProduct()
        // Named string access groups["name"] requires Android API 26 — must not be emitted.
        assertFalse(
            source.contains("groups[\""),
            "Generated handler must NOT use named group string access (requires API 26)."
        )
        // Must use positional index — groups[1] for the first (and only) capture group.
        assertTrue(
            source.contains("groups[1]"),
            "Generated handler must use positional group access groups[1] for first param."
        )
    }

    @Test
    fun buildSource_withMultipleParams_usesSequentialPositionalIndices() {
        val template = DeepLinkTemplateParser.parse("myapp://shop/{category}/{itemId}").getOrThrow()
        val descriptor = descriptor(fqn = "com.example.ShopRoute", templates = listOf(template))
        val source = buildDeepLinkHandlerSource(descriptor)
        assertNotNull(source)
        assertFalse(source.contains("groups[\""), "No named group string access allowed.")
        // category is the 1st capture group → groups[1]; itemId is 2nd → groups[2]
        assertTrue(source.contains("groups[1]"), "First param must use groups[1].")
        assertTrue(source.contains("groups[2]"), "Second param must use groups[2].")
    }

    @Test
    fun buildSource_withTemplate_generatesCanHandleMethod() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("override fun canHandle(uri: String): Boolean"))
        assertTrue(source.contains("containsMatchIn(uri)"))
    }

    @Test
    fun buildSource_multipleTemplates_canHandleChecksAllTemplates() {
        val t0 = DeepLinkTemplateParser.parse("myapp://product/{id}").getOrThrow()
        val t1 = DeepLinkTemplateParser.parse("https://example.com/product/{id}").getOrThrow()
        val descriptor = descriptor("com.example.ProductRoute", templates = listOf(t0, t1))
        val source = buildDeepLinkHandlerSource(descriptor)
        assertNotNull(source)
        assertContains(source, "template0.containsMatchIn(uri)")
        assertContains(source, "template1.containsMatchIn(uri)")
    }

    @Test
    fun buildSource_withTemplate_generatesResolveMethod() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("override fun resolve(uri: String): Route?"))
    }

    @Test
    fun buildSource_withTemplate_resolveUsesCorrectFQN() {
        val source = buildSourceForProduct()
        assertTrue(source.contains("return com.example.ProductDetail("))
    }

    private fun buildSourceForProduct(): String {
        val template = DeepLinkTemplateParser.parse("myapp://product/{productId}").getOrThrow()
        val descriptor = descriptor("com.example.ProductDetail", templates = listOf(template))
        return checkNotNull(buildDeepLinkHandlerSource(descriptor))
    }

    private fun descriptor(
        fqn: String, templates: List<DeepLinkTemplateParser.ParsedTemplate> = emptyList()
    ): RouteDestinationDescriptor {
        val lastDot = fqn.lastIndexOf('.')
        val pkg = if (lastDot >= 0) fqn.substring(0, lastDot) else ""
        val cls = if (lastDot >= 0) fqn.substring(lastDot + 1) else fqn
        return RouteDestinationDescriptor(
            packageName = pkg,
            className = cls,
            canonicalRoute = fqn,
            deepLinkTemplates = templates,
            isSerializable = true
        )
    }
}
